version: '3.9'

services:
  backend:
    container_name: backend
    build: ./backend
    image: backend-image
    ports: 
      - "3000:3000"



  frontend: 
    container_name: frontend
    build: ./frontend
    image: frontend-image
    ports: 
      - "8080:80"
    depends_on:
      - backend
