apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 038675313786.dkr.ecr.us-west-2.amazonaws.com/myapp-backend:latest
        ports:
        - containerPort: 3000

